print("Switching on the camera in the camel habitat...")
print("___.-''''-.")
print("/___  @    |")
print("',,,,.     |         _.''''''''._")
print("     '     |        /           \ ")
print("     |     \    _.-'             \ ")
print("     |      '.-'                  '-.")
print("     |                               ',")
print("     |                                '',")
print("      ',,-,                           ':;")
print("           ',,| ;,,                 ,' ;;")
print("             ! ; !'',,,',',,,,'!  ;   ;:")
print("            : ;  ! !       ! ! ;  ;   :;")
print("            ; ;   ! !      ! !  ; ;   ;,")
print("           ; ;    ! !     ! !   ; ;")
print("           ; ;    ! !    ! !     ; ;")
print("          ;,,      !,!   !,!     ;,;")
print("          /_I      L_I   L_I     /_I")
print("Look at that! Our little camel is sunbathing!")